### ISSUE TITLE
get-aduser userid -Properties * - throws Object reference not set to instance of an object error

### ISSUE THREAD

**Issue by mcurole** [PowerShell/PowerShellModuleCoverage#8] opened 2018-09-14 13:27 UTC
Steps to reproduce
------------------

```powershell
get-aduser userid -Properties *
```

Expected behavior
-----------------

```none
Command should return user and all properties on the account
```

Actual behavior
---------------

```none
get-aduser : Object reference not set to an instance of an object.
At line:1 char:1
+ get-aduser mcuroleadmin -Properties *
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (mcuroleadmin:ADUser) [Get-ADUser], NullReferenceException
+ FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.NullReferenceException,Microsoft.ActiveDirectory.Management.Commands.GetADUser
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17751
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SteveL-MSFT** [comment] 2018-12-05 03:36
This is a dupe of #5

**Closed by SteveL-MSFT** 2018-12-05 03:36 UTC
Labels: duplicate
